from __future__ import annotations

from collections.abc import Callable
from typing import Any

# generate_fn(prompt, schema) -> parsed JSON object (or None). Injected so the
# planning logic is unit-testable without a model.
GenerateFn = Callable[[str, "dict[str, Any]"], "dict[str, Any] | None"]

_PLAN_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "complex": {"type": "boolean"},
        "steps": {"type": "array", "items": {"type": "string"}},
    },
    "required": ["complex", "steps"],
}

_PLAN_PROMPT = (
    "Tu prépares le plan d'exécution d'un agent de codage local. Décide si la "
    "TÂCHE ci-dessous exige réellement PLUSIEURS actions distinctes (plusieurs "
    "fichiers, ou lire puis modifier puis vérifier).\n"
    "- Tâche simple (une question, une seule action) : renvoie complex=false et "
    "steps=[].\n"
    "- Tâche complexe : renvoie complex=true et un plan de 3 à {max_steps} "
    "étapes impératives, concrètes, ordonnées, de moins de 12 mots chacune, "
    "fondées uniquement sur la demande — n'invente ni fichier ni détail. "
    "Commence par une étape de lecture ou d'inspection ; termine par une étape "
    "de vérification (ex. : « Lire le fichier concerné », « Appliquer la "
    "modification », « Lancer les tests »).\n"
    "Ne résous pas la tâche et ne commente pas : seulement la décision et les "
    "étapes.\n\n"
    "TÂCHE : {task}"
)


def build_plan(generate_fn: GenerateFn | None, task: str, *, max_steps: int = 5) -> list[str]:
    """Produce a short ordered plan for a COMPLEX agent task, or ``[]``.

    The model itself decides whether the task warrants a plan (``complex``), so
    a one-shot action or a question never pays the planning tax. 100% local: the
    plan is generated by the same Ollama model via constrained decoding, passed
    in as ``generate_fn``. Never raises — returns ``[]`` on any problem so the
    agent loop just proceeds without a plan.
    """
    cleaned_task = (task or "").strip()
    if not cleaned_task or generate_fn is None:
        return []
    try:
        data = (
            generate_fn(_PLAN_PROMPT.format(task=cleaned_task, max_steps=max_steps), _PLAN_SCHEMA)
            or {}
        )
    except Exception:
        return []
    if not data.get("complex"):
        return []
    steps = data.get("steps")
    if not isinstance(steps, list):
        return []
    cleaned = [str(step).strip() for step in steps if str(step).strip()]
    return cleaned[:max_steps]


def format_plan(steps: list[str]) -> str:
    """Render a plan as agent guidance. Phrased as a proposal (not a rigid
    script) and explicitly NOT to be recited, so the model executes it instead
    of echoing the steps back as its answer."""
    body = "\n".join(f"{index}. {step}" for index, step in enumerate(steps, 1))
    return (
        "[PLAN PROPOSÉ — suis ces étapes dans l'ordre, ajuste-les si la réalité diffère ; "
        "ne les récite pas, exécute-les]\n" + body
    )
